# Generated by Django 3.1.6 on 2021-02-10 23:48

from django.db import migrations

from www.populate_db import populate_db, depopulate_db


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0001_initial"),
    ]

    operations = [migrations.RunPython(populate_db, reverse_code=depopulate_db)]
