# Generated by Django 3.1.5 on 2021-02-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0002_auto_20210201_1241"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="page",
            name="version",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="page",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
