# Generated by Django 3.1.6 on 2021-02-15 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('www', '0003_auto_20210214_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EntityCreator', to=settings.AUTH_USER_MODEL),
        ),
    ]
