# Generated by Django 3.1.7 on 2021-04-04 00:50

from django.db import migrations
import django.db.models.deletion
import markdownfield.models
import shortuuid.main
import shortuuidfield.fields
import www.models.entity


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0003_auto_20210322_2232"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="parent",
            field=www.models.entity.ShortUUIDPolymorphicTreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="www.entity",
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="markdownentity",
            name="markdown",
            field=markdownfield.models.MarkdownField(
                blank=True,
                default="",
                rendered_field="markdown_rendered",
                use_admin_editor=False,
                use_editor=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
