# Generated by Django 3.1.7 on 2021-03-12 19:37

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0003_auto_20210304_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markdownentity",
            name="markdown",
            field=markdownfield.models.MarkdownField(
                blank=True,
                default="",
                rendered_field="markdown_rendered",
                use_editor=False,
            ),
        ),
    ]
