# Generated by Django 3.1.7 on 2021-03-12 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20210312_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
