# Generated by Django 3.2 on 2021-04-15 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedule", "0011_event_calendar_not_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creator",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                help_text="Select '----' for a one time only event.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schedule.rule",
                verbose_name="rule",
            ),
        ),
    ]
