# Generated by Django 3.1.6 on 2021-02-10 23:48

from django.db import migrations, transaction
from www.models import Project, WikiPage, JournalPage, Comment, User, Group


def populate_db_initial(apps, schema_editor):
    with transaction.atomic():
        test_group = Group(name="TestGroup")
        test_group.save()
        test_user = User(
            username="TestUser",
            password="password",
            first_name="Hans",
            last_name="Wurst",
        )
        test_user.save()
        test_user.groups.add(test_group)

        test_project = Project(name="Test Project", key="TEST", creator=test_user)
        test_project.save()
        WikiPage(name="Test Wiki Page", creator=test_user, parent=test_project).save()
        journal = JournalPage(name="Test Journal Page", parent=test_project)
        journal.save()
        WikiPage(name="Orphaned Page", creator=test_user).save()
        Comment(name="First Comment", parent=journal, ENTITY_TYPE="TEST").save()


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0001_initial"),
    ]

    operations = [migrations.RunPython(populate_db_initial)]
